Create Timeline component
channel-io/snippet-web pull request #10
Opened 2020-09-24 07:54 UTC by Junbong

### `Timeline` component
<img width="323" alt="스크린샷 2020-09-24 오후 4 50 07" src="https://user-images.githubusercontent.com/6138662/94116602-3a92e680-fe86-11ea-8720-db359cb1fdda.png">

### `TimelineEventItem` component
<img width="320" alt="스크린샷 2020-09-24 오후 4 50 22" src="https://user-images.githubusercontent.com/6138662/94116552-2b139d80-fe86-11ea-9080-5c36d46ccba3.png">

### Scheme
```
{
	"type": "timeline", // Requirement
	"hour24": true, // Optional. default: false
	"events": [
		{
			"ts": 0, // Requirement
			"value": "", // Requirement
			"color": "white"|"blue"|"cobalt"|"orange"|"red"|"green" // Optional. default: white
		}
	] // Requirement
}
```

2020-09-24 08:09 UTC, jwoo0122 requested changes

2020-09-24 08:09 UTC, jwoo0122 commented on src/components/Timeline/Timeline.stories.tsx
> +  })
storybook 업데이트도 따로 진행을 해야 겠네요

2020-09-24 08:09 UTC, jwoo0122 commented on src/components/Timeline/Timeline.tsx
> +  events?: { ts: number, value: string, color?: string }[]
그런 폴더가 있는지는 모르겠지만 event 타입을 Types 등으로 따로 빼는게 좋을  것 같아요

2020-09-24 08:09 UTC, jwoo0122 commented on src/components/Timeline/Timeline.tsx
> +      )) }
renderContent, renderItems 로 따로 빼고 useMemo 를 쓰는게 어떨까요

2020-09-24 08:09 UTC, jwoo0122 commented on src/components/TimelineEventItem/EventColor.ts
> +enum EventColor {
먼 얘기지만 다크모드에 대한 염두도 하긴 해야겠군요

2020-09-24 08:09 UTC, jwoo0122 commented on src/utils/values.ts
> +/* Internal dependencies */
이건 objectUtils 파일로 만드는 걸 제안합니다

2020-09-25 07:27 UTC, Junbong commented on src/components/TimelineEventItem/EventColor.ts
> +enum EventColor {
여기는 컬러가 스태틱합니다.
라이트한 패키지이므로 다크모드도 일단 고려하지 않습니다.

2020-09-25 07:27 UTC, Junbong commented on package.json
> +  "author": "Channel Corporation",
이건 따로 PR 올릴 예정입니다.

2020-09-25 07:27 UTC, Junbong commented on src/components/Timeline/Timeline.stories.tsx
> +  })
넵 스토리북은 다음 기회에

2020-09-25 07:38 UTC, Junbong commented on src/components/Timeline/Timeline.tsx
> +      )) }
말씀해주신 형태로 나누게 되면 `Object.keys(eventItems)`에 대한 이터레이션을 두 번 돌아야 해서 비효율적이라, 두가지를 합쳐서 한번의 이터레이션으로 useMemo 처리하겠습니다.

2020-09-25 07:39 UTC, Junbong commented on src/components/Timeline/Timeline.tsx
> +      )) }
아, 다시 보니 `map` 내부를 나누자는 말씀이었군요. 일단 하나의 memo로 합쳐서 올릴게요!

2020-09-25 07:58 UTC, Junbong commented on src/utils/values.ts
> +/* Internal dependencies */
프로젝트 구조가, Lodash를 사용하지 않고 필요한 함수를 utils에 하나씩 작성했더라고요.
그래서 기존 구조를 따랐습니다.

![스크린샷 2020-09-25 오후 4 41 22](https://user-images.githubusercontent.com/6138662/94240223-f4a15580-ff4d-11ea-9607-bc651453c662.png)

2020-09-25 08:10 UTC, Junbong commented on src/components/Timeline/Timeline.tsx
> +  events?: { ts: number, value: string, color?: string }[]
그런 폴더는 없습니다. 그래도 이번엔 타입 따로 만들었어요~

2020-09-25 08:19 UTC, jwoo0122 commented on src/components/TimelineEventItem/EventColor.ts
> +enum EventColor {
OK

2020-09-25 08:20 UTC, jwoo0122 commented on src/utils/values.ts
> +/* Internal dependencies */
OK

2020-09-25 08:20 UTC, jwoo0122 approved these changes

2020-09-25 08:20 UTC, jwoo0122 commented on package.json
> +  "author": "Channel Corporation",
OK

2020-09-25 08:37 UTC, groovypark commented on src/components/Timeline/Timeline.tsx
> +            <TimelineEventItem {...others}>
key값 추가해주세요 경고뜨네용

2020-09-25 08:46 UTC, groovypark approved these changes

2020-09-25 09:32 UTC, merged